package modelo;
// Generated 30-may-2024 16:36:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alquilar generated by hbm2java
 */
public class Alquilar  implements java.io.Serializable {


     private Integer id;
     private Propiedades propiedades;
     private Usuarios usuariosByIdPropietario;
     private Usuarios usuariosByIdAlquilado;
     private double precio;
     private Date fechaInicio;
     private Date fechaFin;

    public Alquilar() {
    }

    public Alquilar(Propiedades propiedades, Usuarios usuariosByIdPropietario, Usuarios usuariosByIdAlquilado, double precio, Date fechaInicio, Date fechaFin) {
       this.propiedades = propiedades;
       this.usuariosByIdPropietario = usuariosByIdPropietario;
       this.usuariosByIdAlquilado = usuariosByIdAlquilado;
       this.precio = precio;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuariosByIdPropietario() {
        return this.usuariosByIdPropietario;
    }
    
    public void setUsuariosByIdPropietario(Usuarios usuariosByIdPropietario) {
        this.usuariosByIdPropietario = usuariosByIdPropietario;
    }
    public Usuarios getUsuariosByIdAlquilado() {
        return this.usuariosByIdAlquilado;
    }
    
    public void setUsuariosByIdAlquilado(Usuarios usuariosByIdAlquilado) {
        this.usuariosByIdAlquilado = usuariosByIdAlquilado;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


