package modelo;
// Generated 30-may-2024 16:36:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propiedades generated by hbm2java
 */
public class Propiedades  implements java.io.Serializable {


     private Integer id;
     private Direcciones direcciones;
     private Usuarios usuariosByIdPropietario;
     private Usuarios usuariosByIdInquilino;
     private int superficie;
     private int numeroHabitaciones;
     private byte[] foto;
     private Set visitases = new HashSet(0);
     private Set alquilars = new HashSet(0);
     private Set valoracioneses = new HashSet(0);
     private Set comprars = new HashSet(0);
     private Set favoritoses = new HashSet(0);
     private Set seguroses = new HashSet(0);

    public Propiedades() {
    }

	
    public Propiedades(Direcciones direcciones, Usuarios usuariosByIdPropietario, int superficie, int numeroHabitaciones) {
        this.direcciones = direcciones;
        this.usuariosByIdPropietario = usuariosByIdPropietario;
        this.superficie = superficie;
        this.numeroHabitaciones = numeroHabitaciones;
    }
    public Propiedades(Direcciones direcciones, Usuarios usuariosByIdPropietario, Usuarios usuariosByIdInquilino, int superficie, int numeroHabitaciones, byte[] foto, Set visitases, Set alquilars, Set valoracioneses, Set comprars, Set favoritoses, Set seguroses) {
       this.direcciones = direcciones;
       this.usuariosByIdPropietario = usuariosByIdPropietario;
       this.usuariosByIdInquilino = usuariosByIdInquilino;
       this.superficie = superficie;
       this.numeroHabitaciones = numeroHabitaciones;
       this.foto = foto;
       this.visitases = visitases;
       this.alquilars = alquilars;
       this.valoracioneses = valoracioneses;
       this.comprars = comprars;
       this.favoritoses = favoritoses;
       this.seguroses = seguroses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Direcciones getDirecciones() {
        return this.direcciones;
    }
    
    public void setDirecciones(Direcciones direcciones) {
        this.direcciones = direcciones;
    }
    public Usuarios getUsuariosByIdPropietario() {
        return this.usuariosByIdPropietario;
    }
    
    public void setUsuariosByIdPropietario(Usuarios usuariosByIdPropietario) {
        this.usuariosByIdPropietario = usuariosByIdPropietario;
    }
    public Usuarios getUsuariosByIdInquilino() {
        return this.usuariosByIdInquilino;
    }
    
    public void setUsuariosByIdInquilino(Usuarios usuariosByIdInquilino) {
        this.usuariosByIdInquilino = usuariosByIdInquilino;
    }
    public int getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(int superficie) {
        this.superficie = superficie;
    }
    public int getNumeroHabitaciones() {
        return this.numeroHabitaciones;
    }
    
    public void setNumeroHabitaciones(int numeroHabitaciones) {
        this.numeroHabitaciones = numeroHabitaciones;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getVisitases() {
        return this.visitases;
    }
    
    public void setVisitases(Set visitases) {
        this.visitases = visitases;
    }
    public Set getAlquilars() {
        return this.alquilars;
    }
    
    public void setAlquilars(Set alquilars) {
        this.alquilars = alquilars;
    }
    public Set getValoracioneses() {
        return this.valoracioneses;
    }
    
    public void setValoracioneses(Set valoracioneses) {
        this.valoracioneses = valoracioneses;
    }
    public Set getComprars() {
        return this.comprars;
    }
    
    public void setComprars(Set comprars) {
        this.comprars = comprars;
    }
    public Set getFavoritoses() {
        return this.favoritoses;
    }
    
    public void setFavoritoses(Set favoritoses) {
        this.favoritoses = favoritoses;
    }
    public Set getSeguroses() {
        return this.seguroses;
    }
    
    public void setSeguroses(Set seguroses) {
        this.seguroses = seguroses;
    }




}


