package modelo;
// Generated 30-may-2024 16:36:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Seguros generated by hbm2java
 */
public class Seguros  implements java.io.Serializable {


     private Integer id;
     private Propiedades propiedades;
     private Usuarios usuarios;
     private String cobertura;
     private double tarifa;
     private Date fechaInicio;
     private Date fechaFin;

    public Seguros() {
    }

    public Seguros(Propiedades propiedades, Usuarios usuarios, String cobertura, double tarifa, Date fechaInicio, Date fechaFin) {
       this.propiedades = propiedades;
       this.usuarios = usuarios;
       this.cobertura = cobertura;
       this.tarifa = tarifa;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getCobertura() {
        return this.cobertura;
    }
    
    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }
    public double getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(double tarifa) {
        this.tarifa = tarifa;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


