package modelo;
// Generated 30-may-2024 16:36:51 by Hibernate Tools 4.3.1



/**
 * Valoraciones generated by hbm2java
 */
public class Valoraciones  implements java.io.Serializable {


     private Integer id;
     private Propiedades propiedades;
     private Usuarios usuarios;
     private double puntuacion;

    public Valoraciones() {
    }

    public Valoraciones(Propiedades propiedades, Usuarios usuarios, double puntuacion) {
       this.propiedades = propiedades;
       this.usuarios = usuarios;
       this.puntuacion = puntuacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public double getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(double puntuacion) {
        this.puntuacion = puntuacion;
    }




}


