package modelo;
// Generated 30-may-2024 16:36:51 by Hibernate Tools 4.3.1



/**
 * Visitas generated by hbm2java
 */
public class Visitas  implements java.io.Serializable {


     private Integer id;
     private Propiedades propiedades;
     private Usuarios usuarios;
     private int duracion;

    public Visitas() {
    }

    public Visitas(Propiedades propiedades, Usuarios usuarios, int duracion) {
       this.propiedades = propiedades;
       this.usuarios = usuarios;
       this.duracion = duracion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


