package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  implements java.io.Serializable {


     private int id;
     private Propiedades propiedades;
     private Usuarios usuariosByIdInquilino;
     private Usuarios usuariosByIdPropietario;
     private double precio;
     private Date fechaInicio;
     private Date fechaFin;

    public Alquiler() {
    }

    public Alquiler(int id, Propiedades propiedades, Usuarios usuariosByIdInquilino, Usuarios usuariosByIdPropietario, double precio, Date fechaInicio, Date fechaFin) {
       this.id = id;
       this.propiedades = propiedades;
       this.usuariosByIdInquilino = usuariosByIdInquilino;
       this.usuariosByIdPropietario = usuariosByIdPropietario;
       this.precio = precio;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuariosByIdInquilino() {
        return this.usuariosByIdInquilino;
    }
    
    public void setUsuariosByIdInquilino(Usuarios usuariosByIdInquilino) {
        this.usuariosByIdInquilino = usuariosByIdInquilino;
    }
    public Usuarios getUsuariosByIdPropietario() {
        return this.usuariosByIdPropietario;
    }
    
    public void setUsuariosByIdPropietario(Usuarios usuariosByIdPropietario) {
        this.usuariosByIdPropietario = usuariosByIdPropietario;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


