package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comprar generated by hbm2java
 */
public class Comprar  implements java.io.Serializable {


     private int id;
     private Propiedades propiedades;
     private Usuarios usuariosByIdComprador;
     private Usuarios usuariosByIdVendedor;
     private double precio;
     private Date fecha;

    public Comprar() {
    }

    public Comprar(int id, Propiedades propiedades, Usuarios usuariosByIdComprador, Usuarios usuariosByIdVendedor, double precio, Date fecha) {
       this.id = id;
       this.propiedades = propiedades;
       this.usuariosByIdComprador = usuariosByIdComprador;
       this.usuariosByIdVendedor = usuariosByIdVendedor;
       this.precio = precio;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuariosByIdComprador() {
        return this.usuariosByIdComprador;
    }
    
    public void setUsuariosByIdComprador(Usuarios usuariosByIdComprador) {
        this.usuariosByIdComprador = usuariosByIdComprador;
    }
    public Usuarios getUsuariosByIdVendedor() {
        return this.usuariosByIdVendedor;
    }
    
    public void setUsuariosByIdVendedor(Usuarios usuariosByIdVendedor) {
        this.usuariosByIdVendedor = usuariosByIdVendedor;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


