package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private int id;
     private String calle;
     private int numero;
     private int codigoPostal;
     private String ciudad;
     private String provincia;
     private String pais;
     private Set propiedadeses = new HashSet(0);

    public Direccion() {
    }

	
    public Direccion(int id, String calle, int numero, int codigoPostal, String ciudad, String provincia, String pais) {
        this.id = id;
        this.calle = calle;
        this.numero = numero;
        this.codigoPostal = codigoPostal;
        this.ciudad = ciudad;
        this.provincia = provincia;
        this.pais = pais;
    }
    public Direccion(int id, String calle, int numero, int codigoPostal, String ciudad, String provincia, String pais, Set propiedadeses) {
       this.id = id;
       this.calle = calle;
       this.numero = numero;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.pais = pais;
       this.propiedadeses = propiedadeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set propiedadeses) {
        this.propiedadeses = propiedadeses;
    }




}


