package modelos;
// Generated 30-may-2024 16:36:51 by Hibernate Tools 4.3.1



/**
 * Favoritos generated by hbm2java
 */
public class Favoritos  implements java.io.Serializable {


     private Integer id;
     private Propiedades propiedades;
     private Usuarios usuarios;

    public Favoritos() {
    }

    public Favoritos(Propiedades propiedades, Usuarios usuarios) {
       this.propiedades = propiedades;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


