package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1



/**
 * Lineamobiliario generated by hbm2java
 */
public class Lineamobiliario  implements java.io.Serializable {


     private int id;
     private Mobiliario mobiliario;
     private Propiedades propiedades;

    public Lineamobiliario() {
    }

    public Lineamobiliario(int id, Mobiliario mobiliario, Propiedades propiedades) {
       this.id = id;
       this.mobiliario = mobiliario;
       this.propiedades = propiedades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mobiliario getMobiliario() {
        return this.mobiliario;
    }
    
    public void setMobiliario(Mobiliario mobiliario) {
        this.mobiliario = mobiliario;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }




}


