package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mobiliario generated by hbm2java
 */
public class Mobiliario  implements java.io.Serializable {


     private int id;
     private String mueble;
     private Set lineamobiliarios = new HashSet(0);

    public Mobiliario() {
    }

	
    public Mobiliario(int id, String mueble) {
        this.id = id;
        this.mueble = mueble;
    }
    public Mobiliario(int id, String mueble, Set lineamobiliarios) {
       this.id = id;
       this.mueble = mueble;
       this.lineamobiliarios = lineamobiliarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMueble() {
        return this.mueble;
    }
    
    public void setMueble(String mueble) {
        this.mueble = mueble;
    }
    public Set getLineamobiliarios() {
        return this.lineamobiliarios;
    }
    
    public void setLineamobiliarios(Set lineamobiliarios) {
        this.lineamobiliarios = lineamobiliarios;
    }




}


