package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propiedades generated by hbm2java
 */
public class Propiedades  implements java.io.Serializable {


     private int id;
     private Direccion direccion;
     private Usuarios usuariosByIdPropietario;
     private Usuarios usuariosByIdInquilino;
     private int superficie;
     private int numeroHabitaciones;
     private Set valoracionpropiedads = new HashSet(0);
     private Set comprars = new HashSet(0);
     private Set seguros = new HashSet(0);
     private Set visitas = new HashSet(0);
     private Set alquilers = new HashSet(0);
     private Set lineamobiliarios = new HashSet(0);

    public Propiedades() {
    }

	
    public Propiedades(int id, Direccion direccion, Usuarios usuariosByIdPropietario, int superficie, int numeroHabitaciones) {
        this.id = id;
        this.direccion = direccion;
        this.usuariosByIdPropietario = usuariosByIdPropietario;
        this.superficie = superficie;
        this.numeroHabitaciones = numeroHabitaciones;
    }
    public Propiedades(int id, Direccion direccion, Usuarios usuariosByIdPropietario, Usuarios usuariosByIdInquilino, int superficie, int numeroHabitaciones, Set valoracionpropiedads, Set comprars, Set seguros, Set visitas, Set alquilers, Set lineamobiliarios) {
       this.id = id;
       this.direccion = direccion;
       this.usuariosByIdPropietario = usuariosByIdPropietario;
       this.usuariosByIdInquilino = usuariosByIdInquilino;
       this.superficie = superficie;
       this.numeroHabitaciones = numeroHabitaciones;
       this.valoracionpropiedads = valoracionpropiedads;
       this.comprars = comprars;
       this.seguros = seguros;
       this.visitas = visitas;
       this.alquilers = alquilers;
       this.lineamobiliarios = lineamobiliarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Usuarios getUsuariosByIdPropietario() {
        return this.usuariosByIdPropietario;
    }
    
    public void setUsuariosByIdPropietario(Usuarios usuariosByIdPropietario) {
        this.usuariosByIdPropietario = usuariosByIdPropietario;
    }
    public Usuarios getUsuariosByIdInquilino() {
        return this.usuariosByIdInquilino;
    }
    
    public void setUsuariosByIdInquilino(Usuarios usuariosByIdInquilino) {
        this.usuariosByIdInquilino = usuariosByIdInquilino;
    }
    public int getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(int superficie) {
        this.superficie = superficie;
    }
    public int getNumeroHabitaciones() {
        return this.numeroHabitaciones;
    }
    
    public void setNumeroHabitaciones(int numeroHabitaciones) {
        this.numeroHabitaciones = numeroHabitaciones;
    }
    public Set getValoracionpropiedads() {
        return this.valoracionpropiedads;
    }
    
    public void setValoracionpropiedads(Set valoracionpropiedads) {
        this.valoracionpropiedads = valoracionpropiedads;
    }
    public Set getComprars() {
        return this.comprars;
    }
    
    public void setComprars(Set comprars) {
        this.comprars = comprars;
    }
    public Set getSeguros() {
        return this.seguros;
    }
    
    public void setSeguros(Set seguros) {
        this.seguros = seguros;
    }
    public Set getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Set visitas) {
        this.visitas = visitas;
    }
    public Set getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set alquilers) {
        this.alquilers = alquilers;
    }
    public Set getLineamobiliarios() {
        return this.lineamobiliarios;
    }
    
    public void setLineamobiliarios(Set lineamobiliarios) {
        this.lineamobiliarios = lineamobiliarios;
    }




}


