package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1



/**
 * Valoracionpropiedad generated by hbm2java
 */
public class Valoracionpropiedad  implements java.io.Serializable {


     private int id;
     private Propiedades propiedades;
     private Usuarios usuarios;
     private double puntuacion;

    public Valoracionpropiedad() {
    }

    public Valoracionpropiedad(int id, Propiedades propiedades, Usuarios usuarios, double puntuacion) {
       this.id = id;
       this.propiedades = propiedades;
       this.usuarios = usuarios;
       this.puntuacion = puntuacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public double getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(double puntuacion) {
        this.puntuacion = puntuacion;
    }




}


