package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1



/**
 * Valoracionusuario generated by hbm2java
 */
public class Valoracionusuario  implements java.io.Serializable {


     private int id;
     private Usuarios usuariosByIdUsuario;
     private Usuarios usuariosByIdValorador;
     private double puntuacion;

    public Valoracionusuario() {
    }

    public Valoracionusuario(int id, Usuarios usuariosByIdUsuario, Usuarios usuariosByIdValorador, double puntuacion) {
       this.id = id;
       this.usuariosByIdUsuario = usuariosByIdUsuario;
       this.usuariosByIdValorador = usuariosByIdValorador;
       this.puntuacion = puntuacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuarios getUsuariosByIdUsuario() {
        return this.usuariosByIdUsuario;
    }
    
    public void setUsuariosByIdUsuario(Usuarios usuariosByIdUsuario) {
        this.usuariosByIdUsuario = usuariosByIdUsuario;
    }
    public Usuarios getUsuariosByIdValorador() {
        return this.usuariosByIdValorador;
    }
    
    public void setUsuariosByIdValorador(Usuarios usuariosByIdValorador) {
        this.usuariosByIdValorador = usuariosByIdValorador;
    }
    public double getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(double puntuacion) {
        this.puntuacion = puntuacion;
    }




}


