package modelos;
// Generated 18-may-2024 17:30:18 by Hibernate Tools 4.3.1



/**
 * Visita generated by hbm2java
 */
public class Visita  implements java.io.Serializable {


     private int id;
     private Propiedades propiedades;
     private Usuarios usuarios;
     private int duracion;

    public Visita() {
    }

    public Visita(int id, Propiedades propiedades, Usuarios usuarios, int duracion) {
       this.id = id;
       this.propiedades = propiedades;
       this.usuarios = usuarios;
       this.duracion = duracion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


